services:
  pg:
    image: postgres
    volumes:
      - pg:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
volumes:
  pg:
