"""create tables recipes ingredients

Revision ID: 1bd153348810
Revises: 
Create Date: 2024-11-07 11:33:35.404467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1bd153348810"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingredient_name", sa.String(length=100), nullable=False),
        sa.Column("ingredient_description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_name", sa.String(length=100), nullable=False),
        sa.Column("cooking_time", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("recipe_description", sa.Text(), nullable=False),

        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipes")
    op.drop_table("ingredients")
    # ### end Alembic commands ###
